### ISSUE TITLE
Bug: NPM error - PWA support is disabled

### ISSUE THREAD

**Issue by jstnbr** [katherinepeterson/readme.so#289]
**Describe the bug**
I am trying to run the dev server locally by cloning and running `npm run dev`, but I get an error.

**To Reproduce**

1. Clone the repository
2. CD into repo, and run `npm install`
3. Then run `npm run dev`

**Expected behavior**
A dev server should be running on `http://localhost:3000`

After cloning the repo, I ran `npm install`, then I ran `npm run dev`. I did not change anything else, perhaps I missed a step. The output for both is below. I think the error has to do with PWA support. Here's the full output of the error I receive:

`npm install` output:

```
> readme.so@0.1.0 postinstall
> husky install

husky - not a Git repository, skipping hooks installation

up to date, audited 1579 packages in 3s

142 packages are looking for funding
  run `npm fund` for details

41 vulnerabilities (13 moderate, 14 high, 14 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```

`npm run dev` output:

```
> readme.so@0.1.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
> [PWA] PWA support is disabled
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/Users/jstn/readme-so/node_modules/next/dist/compiled/webpack/bundle5.js:138971:18)
    at BulkUpdateDecorator.update (/Users/jstn/readme-so/node_modules/next/dist/compiled/webpack/bundle5.js:138872:50)
    at OriginalSource.updateHash (/Users/jstn/readme-so/node_modules/next/dist/compiled/webpack-sources3/index.js:1:10264)
    at NormalModule._initBuildHash (/Users/jstn/readme-so/node_modules/next/dist/compiled/webpack/bundle5.js:68468:17)
    at handleParseResult (/Users/jstn/readme-so/node_modules/next/dist/compiled/webpack/bundle5.js:68534:10)
    at /Users/jstn/readme-so/node_modules/next/dist/compiled/webpack/bundle5.js:68628:4
    at processResult (/Users/jstn/readme-so/node_modules/next/dist/compiled/webpack/bundle5.js:68343:11)
    at /Users/jstn/readme-so/node_modules/next/dist/compiled/webpack/bundle5.js:68407:5
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/Users/jstn/readme-so/node_modules/next/dist/compiled/webpack/bundle5.js:138971:18)
    at BulkUpdateDecorator.update (/Users/jstn/readme-so/node_modules/next/dist/compiled/webpack/bundle5.js:138872:50)
    at OriginalSource.updateHash (/Users/jstn/readme-so/node_modules/next/dist/compiled/webpack-sources3/index.js:1:10264)
    at NormalModule._initBuildHash (/Users/jstn/readme-so/node_modules/next/dist/compiled/webpack/bundle5.js:68468:17)
    at handleParseResult (/Users/jstn/readme-so/node_modules/next/dist/compiled/webpack/bundle5.js:68534:10)
    at /Users/jstn/readme-so/node_modules/next/dist/compiled/webpack/bundle5.js:68628:4
    at processResult (/Users/jstn/readme-so/node_modules/next/dist/compiled/webpack/bundle5.js:68343:11)
    at /Users/jstn/readme-so/node_modules/next/dist/compiled/webpack/bundle5.js:68407:5
node:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/Users/jstn/readme-so/node_modules/next/dist/compiled/webpack/bundle5.js:138971:18)
    at BulkUpdateDecorator.update (/Users/jstn/readme-so/node_modules/next/dist/compiled/webpack/bundle5.js:138872:50)
    at OriginalSource.updateHash (/Users/jstn/readme-so/node_modules/next/dist/compiled/webpack-sources3/index.js:1:10264)
    at NormalModule._initBuildHash (/Users/jstn/readme-so/node_modules/next/dist/compiled/webpack/bundle5.js:68468:17)
    at handleParseResult (/Users/jstn/readme-so/node_modules/next/dist/compiled/webpack/bundle5.js:68534:10)
    at /Users/jstn/readme-so/node_modules/next/dist/compiled/webpack/bundle5.js:68628:4
    at processResult (/Users/jstn/readme-so/node_modules/next/dist/compiled/webpack/bundle5.js:68343:11)
    at /Users/jstn/readme-so/node_modules/next/dist/compiled/webpack/bundle5.js:68407:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.17.1
```

**Comment by DomeT99** [comment]
Hi @jstnbr 
I'm having the same problem too.
To fix it you should use a version of Node.js < 18.x.x (for example 16.x.x).

If you use another version, run `npm install` and run `npm run dev`, now work!

**Comment by johnblommers** [comment]
Alas, the above steps do not work when using Node.js v21.7.3 as the self-same error appears.
